# Generated by Django 3.2.16 on 2023-01-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='emails',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
