# Generated by Django 3.2.16 on 2023-01-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20230111_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
